name: Build LootLogger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install --omit=dev
        
      - name: Create package folder
        run: mkdir loot-logger
        
      - name: Copy assets
        run: |
          xcopy /E /I node_modules loot-logger\node_modules
          xcopy /E /I src loot-logger\src
          copy package.json loot-logger\
          
      - name: Install caxa
        run: npm install --global caxa
        
      - name: Package the app
        run: caxa --input loot-logger --output "loot-logger-win.exe" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/src/index.js"
        
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: loot-logger-windows
          path: loot-logger-win.exe
          if-no-files-found: error

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev
          
      - name: Install dependencies
        run: npm install --omit=dev
        
      - name: Create package folder
        run: mkdir -p loot-logger
        
      - name: Copy assets
        run: |
          cp -r node_modules/ loot-logger/
          cp -r src/ loot-logger/
          cp package.json loot-logger/
          
      - name: Install caxa
        run: npm install --global caxa
        
      - name: Package the app
        run: caxa --input loot-logger --output "loot-logger-linux" -- "{{caxa}}/node_modules/.bin/node" "{{caxa}}/src/index.js"
        
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: loot-logger-linux
          path: loot-logger-linux
          if-no-files-found: error

  release:
    if: github.event_name == 'release'
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: loot-logger-windows
          
      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: loot-logger-linux
          
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            loot-logger-win.exe
            loot-logger-linux
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
